
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    jndi-name: jdbc/space-app
  output:
    ansi:
      enabled: always

logging:
  #config: classpath:logback-spring.xml
  #config: classpath:logback.xml

server:
  shutdown: graceful
  port: 7200
  tomcat:
    threads:
      max: 20
    max-swallow-size: 2MB
  max-http-header-size: 8KB

security:
  reject-public-invocations: false

# schedule 설정
schedule:
  apitxlog:
    enabled: false
  session-status-mng:
    enabled: false
  sqlmap-reload:
    enabled: true

# file 설정
file:
  upload:
    dirpath: "/data/pilot/%1$tY/%1$tm"
    filename: "%1$tY%1$tm%1$td_%2$s_%3$s.%4$s"

