
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    jndi-name: jdbc/space-app
  output:
    ansi:
      enabled: always

logging:
  level:
    root: info

server:
  shutdown: graceful
  port: 7100
  tomcat:
    threads:
      max: 20
    max-swallow-size: 2MB
  max-http-header-size: 8KB

security:
  rejectPublicInvocations: false

